---
- hosts: node3
  vars_files:
    - ./wordpress/vars/wordpress.yml
  roles:
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.php }
    - { role: geerlingguy.mysql }
    - { role: wordpress }