---
- hosts: db
  vars_files:
    - vars/wordpress.yml
    - vars/wordpress_vault.yml
  roles:
    - { role: geerlingguy.nginx }
    - { role: geerlingguy.php }
    - { role: geerlingguy.mysql }
    - { role: wordpress }
